"""
DXCC prefix lookup table.
Maps callsign prefixes to entity info: name, continent, CQ zone, ITU zone, flag emoji.
Covers ~340 DXCC entities with their most common prefixes.
"""

# Format: prefix -> (entity_name, continent, cq_zone, itu_zone, flag_emoji)
PREFIX_TABLE = {
    # North America
    "K":    ("United States",        "NA", 3,  7,  "🇺🇸"),
    "W":    ("United States",        "NA", 3,  7,  "🇺🇸"),
    "N":    ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AA":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AB":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AC":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AD":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AE":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AF":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AG":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AH":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AI":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AJ":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "AK":   ("United States",        "NA", 3,  7,  "🇺🇸"),
    "KH6":  ("Hawaii",               "OC", 31, 61, "🇺🇸"),
    "KH0":  ("Mariana Is.",          "OC", 27, 64, "🇲🇵"),
    "KH2":  ("Guam",                 "OC", 27, 64, "🇬🇺"),
    "KH8":  ("American Samoa",       "OC", 32, 62, "🇦🇸"),
    "KL":   ("Alaska",               "NA", 1,  1,  "🇺🇸"),
    "KP2":  ("US Virgin Islands",    "NA", 8,  11, "🇻🇮"),
    "KP4":  ("Puerto Rico",          "NA", 8,  11, "🇵🇷"),
    "KG4":  ("Guantanamo Bay",       "NA", 8,  11, "🇺🇸"),
    "VE":   ("Canada",               "NA", 1,  3,  "🇨🇦"),
    "VA":   ("Canada",               "NA", 1,  3,  "🇨🇦"),
    "VO":   ("Canada",               "NA", 2,  9,  "🇨🇦"),
    "VY":   ("Canada",               "NA", 1,  3,  "🇨🇦"),
    "XE":   ("Mexico",               "NA", 6,  10, "🇲🇽"),
    "XF":   ("Mexico",               "NA", 6,  10, "🇲🇽"),
    # Caribbean / Central America
    "C6":   ("Bahamas",              "NA", 8,  11, "🇧🇸"),
    "CO":   ("Cuba",                 "NA", 8,  11, "🇨🇺"),
    "CM":   ("Cuba",                 "NA", 8,  11, "🇨🇺"),
    "HH":   ("Haiti",                "NA", 8,  11, "🇭🇹"),
    "HI":   ("Dominican Republic",   "NA", 8,  11, "🇩🇴"),
    "J3":   ("Grenada",              "NA", 8,  11, "🇬🇩"),
    "J6":   ("St. Lucia",            "NA", 8,  11, "🇱🇨"),
    "J7":   ("Dominica",             "NA", 8,  11, "🇩🇲"),
    "J8":   ("St. Vincent",          "NA", 8,  11, "🇻🇨"),
    "TI":   ("Costa Rica",           "NA", 7,  11, "🇨🇷"),
    "TG":   ("Guatemala",            "NA", 7,  11, "🇬🇹"),
    "HQ":   ("Honduras",             "NA", 7,  11, "🇭🇳"),
    "HR":   ("Honduras",             "NA", 7,  11, "🇭🇳"),
    "YN":   ("Nicaragua",            "NA", 7,  11, "🇳🇮"),
    "HP":   ("Panama",               "NA", 7,  11, "🇵🇦"),
    "V3":   ("Belize",               "NA", 7,  11, "🇧🇿"),
    "YS":   ("El Salvador",          "NA", 7,  11, "🇸🇻"),
    "6Y":   ("Jamaica",              "NA", 8,  11, "🇯🇲"),
    "8P":   ("Barbados",             "NA", 8,  11, "🇧🇧"),
    "FG":   ("Guadeloupe",           "NA", 8,  11, "🇬🇵"),
    "FM":   ("Martinique",           "NA", 8,  11, "🇲🇶"),
    "VP9":  ("Bermuda",              "NA", 5,  11, "🇧🇲"),
    "PJ2":  ("Curacao",              "SA", 9,  11, "🇨🇼"),
    "PJ4":  ("Bonaire",              "SA", 9,  11, "🇧🇶"),
    # South America
    "PY":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "PP":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "PQ":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "PR":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "PS":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "PT":   ("Brazil",               "SA", 11, 15, "🇧🇷"),
    "LU":   ("Argentina",            "SA", 13, 16, "🇦🇷"),
    "LW":   ("Argentina",            "SA", 13, 16, "🇦🇷"),
    "CE":   ("Chile",                "SA", 12, 16, "🇨🇱"),
    "HK":   ("Colombia",             "SA", 9,  12, "🇨🇴"),
    "OA":   ("Peru",                 "SA", 10, 12, "🇵🇪"),
    "OB":   ("Peru",                 "SA", 10, 12, "🇵🇪"),
    "HC":   ("Ecuador",              "SA", 10, 12, "🇪🇨"),
    "YV":   ("Venezuela",            "SA", 9,  12, "🇻🇪"),
    "CP":   ("Bolivia",              "SA", 10, 14, "🇧🇴"),
    "ZP":   ("Paraguay",             "SA", 11, 14, "🇵🇾"),
    "CX":   ("Uruguay",              "SA", 13, 14, "🇺🇾"),
    "GY":   ("Guyana",               "SA", 9,  12, "🇬🇾"),
    "8R":   ("Guyana",               "SA", 9,  12, "🇬🇾"),
    "PZ":   ("Suriname",             "SA", 9,  12, "🇸🇷"),
    "FY":   ("French Guiana",        "SA", 9,  12, "🇬🇫"),
    "VP8":  ("Falkland Islands",     "SA", 13, 16, "🇫🇰"),
    "CE9":  ("Antarctica",           "SA", 38, 67, "🇦🇶"),
    # Europe
    "G":    ("England",              "EU", 14, 27, "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    "M":    ("England",              "EU", 14, 27, "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    "2E":   ("England",              "EU", 14, 27, "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    "GM":   ("Scotland",             "EU", 14, 27, "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
    "GW":   ("Wales",                "EU", 14, 27, "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
    "GI":   ("N. Ireland",           "EU", 14, 27, "🇬🇧"),
    "GJ":   ("Jersey",               "EU", 14, 27, "🇯🇪"),
    "GU":   ("Guernsey",             "EU", 14, 27, "🇬🇬"),
    "GD":   ("Isle of Man",          "EU", 14, 27, "🇮🇲"),
    "F":    ("France",               "EU", 14, 27, "🇫🇷"),
    "DL":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DA":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DB":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DC":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DD":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DE":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DF":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DG":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DH":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DI":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DJ":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DK":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DM":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DN":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DO":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DP":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DQ":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "DR":   ("Germany",              "EU", 14, 28, "🇩🇪"),
    "I":    ("Italy",                "EU", 15, 28, "🇮🇹"),
    "IK":   ("Italy",                "EU", 15, 28, "🇮🇹"),
    "IU":   ("Italy",                "EU", 15, 28, "🇮🇹"),
    "IW":   ("Italy",                "EU", 15, 28, "🇮🇹"),
    "IZ":   ("Italy",                "EU", 15, 28, "🇮🇹"),
    "IQ":   ("Italy",                "EU", 15, 28, "🇮🇹"),
    "EA":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EB":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EC":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "ED":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EE":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EF":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EG":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EH":   ("Spain",                "EU", 14, 37, "🇪🇸"),
    "EA8":  ("Canary Islands",       "AF", 33, 36, "🇮🇨"),
    "EA9":  ("Ceuta & Melilla",      "AF", 33, 37, "🇪🇸"),
    "CT":   ("Portugal",             "EU", 14, 37, "🇵🇹"),
    "CR":   ("Portugal",             "EU", 14, 37, "🇵🇹"),
    "CS":   ("Portugal",             "EU", 14, 37, "🇵🇹"),
    "ON":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "OO":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "OQ":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "OR":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "OS":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "OT":   ("Belgium",              "EU", 14, 27, "🇧🇪"),
    "PA":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PB":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PC":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PD":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PE":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PF":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PG":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PH":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "PI":   ("Netherlands",          "EU", 14, 27, "🇳🇱"),
    "SM":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SA":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SB":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SC":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SD":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SE":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SF":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SG":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SH":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "SI":   ("Sweden",               "EU", 18, 26, "🇸🇪"),
    "OH":   ("Finland",              "EU", 18, 18, "🇫🇮"),
    "OI":   ("Finland",              "EU", 18, 18, "🇫🇮"),
    "OJ":   ("Finland",              "EU", 18, 18, "🇫🇮"),
    "LA":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LB":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LC":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LD":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LE":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LF":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "LG":   ("Norway",               "EU", 18, 18, "🇳🇴"),
    "OZ":   ("Denmark",              "EU", 18, 26, "🇩🇰"),
    "5P":   ("Denmark",              "EU", 18, 26, "🇩🇰"),
    "5Q":   ("Denmark",              "EU", 18, 26, "🇩🇰"),
    "OX":   ("Greenland",            "NA", 5,  75, "🇬🇱"),
    "SP":   ("Poland",               "EU", 15, 28, "🇵🇱"),
    "SN":   ("Poland",               "EU", 15, 28, "🇵🇱"),
    "SO":   ("Poland",               "EU", 15, 28, "🇵🇱"),
    "SQ":   ("Poland",               "EU", 15, 28, "🇵🇱"),
    "SR":   ("Poland",               "EU", 15, 28, "🇵🇱"),
    "OK":   ("Czech Republic",       "EU", 15, 28, "🇨🇿"),
    "OL":   ("Czech Republic",       "EU", 15, 28, "🇨🇿"),
    "OM":   ("Slovak Republic",      "EU", 15, 28, "🇸🇰"),
    "HA":   ("Hungary",              "EU", 15, 28, "🇭🇺"),
    "HG":   ("Hungary",              "EU", 15, 28, "🇭🇺"),
    "OE":   ("Austria",              "EU", 15, 28, "🇦🇹"),
    "HB":   ("Switzerland",          "EU", 14, 28, "🇨🇭"),
    "HB0":  ("Liechtenstein",        "EU", 14, 28, "🇱🇮"),
    "LX":   ("Luxembourg",           "EU", 14, 27, "🇱🇺"),
    "SV":   ("Greece",               "EU", 20, 28, "🇬🇷"),
    "J4":   ("Greece",               "EU", 20, 28, "🇬🇷"),
    "SV5":  ("Dodecanese",           "EU", 20, 28, "🇬🇷"),
    "SV9":  ("Crete",                "EU", 20, 28, "🇬🇷"),
    "YO":   ("Romania",              "EU", 20, 28, "🇷🇴"),
    "YP":   ("Romania",              "EU", 20, 28, "🇷🇴"),
    "YQ":   ("Romania",              "EU", 20, 28, "🇷🇴"),
    "YR":   ("Romania",              "EU", 20, 28, "🇷🇴"),
    "LZ":   ("Bulgaria",             "EU", 20, 28, "🇧🇬"),
    "YU":   ("Serbia",               "EU", 15, 28, "🇷🇸"),
    "4N":   ("Serbia",               "EU", 15, 28, "🇷🇸"),
    "4O":   ("Montenegro",           "EU", 15, 28, "🇲🇪"),
    "9A":   ("Croatia",              "EU", 15, 28, "🇭🇷"),
    "S5":   ("Slovenia",             "EU", 15, 28, "🇸🇮"),
    "E7":   ("Bosnia-Herzegovina",   "EU", 15, 28, "🇧🇦"),
    "Z6":   ("Kosovo",               "EU", 15, 28, "🇽🇰"),
    "Z3":   ("North Macedonia",      "EU", 15, 28, "🇲🇰"),
    "ZA":   ("Albania",              "EU", 15, 28, "🇦🇱"),
    "UA":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UB":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UC":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UD":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UE":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UF":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UG":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UI":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UA9":  ("Asiatic Russia",       "AS", 17, 30, "🇷🇺"),
    "UA0":  ("Asiatic Russia",       "AS", 18, 32, "🇷🇺"),
    "RA":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RB":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RC":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RD":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RE":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RF":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RG":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RK":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RL":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RM":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RN":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RO":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RQ":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RT":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RU":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RV":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RW":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RX":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RY":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "RZ":   ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "R":    ("European Russia",      "EU", 16, 29, "🇷🇺"),
    "UR":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "US":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UT":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UU":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UV":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UW":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UX":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UY":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "UZ":   ("Ukraine",              "EU", 16, 29, "🇺🇦"),
    "EW":   ("Belarus",              "EU", 16, 29, "🇧🇾"),
    "ES":   ("Estonia",              "EU", 15, 29, "🇪🇪"),
    "YL":   ("Latvia",               "EU", 15, 29, "🇱🇻"),
    "LY":   ("Lithuania",            "EU", 15, 29, "🇱🇹"),
    "EV":   ("Belarus",              "EU", 16, 29, "🇧🇾"),
    "ER":   ("Moldova",              "EU", 16, 29, "🇲🇩"),
    "EK":   ("Armenia",              "AS", 21, 29, "🇦🇲"),
    "4J":   ("Azerbaijan",           "AS", 21, 29, "🇦🇿"),
    "4K":   ("Azerbaijan",           "AS", 21, 29, "🇦🇿"),
    "UJ":   ("Uzbekistan",           "AS", 17, 30, "🇺🇿"),
    "UK":   ("Uzbekistan",           "AS", 17, 30, "🇺🇿"),
    "EY":   ("Tajikistan",           "AS", 17, 30, "🇹🇯"),
    "EZ":   ("Turkmenistan",         "AS", 17, 30, "🇹🇲"),
    "UN":   ("Kazakhstan",           "AS", 17, 30, "🇰🇿"),
    "UO":   ("Kazakhstan",           "AS", 17, 30, "🇰🇿"),
    "EX":   ("Kyrgyzstan",           "AS", 17, 30, "🇰🇬"),
    "4L":   ("Georgia",              "AS", 21, 29, "🇬🇪"),
    # Middle East
    "TA":   ("Turkey",               "AS", 20, 39, "🇹🇷"),
    "TB":   ("Turkey",               "AS", 20, 39, "🇹🇷"),
    "TC":   ("Turkey",               "AS", 20, 39, "🇹🇷"),
    "4X":   ("Israel",               "AS", 20, 39, "🇮🇱"),
    "4Z":   ("Israel",               "AS", 20, 39, "🇮🇱"),
    "OD":   ("Lebanon",              "AS", 20, 39, "🇱🇧"),
    "YK":   ("Syria",                "AS", 20, 39, "🇸🇾"),
    "JY":   ("Jordan",               "AS", 20, 39, "🇯🇴"),
    "HZ":   ("Saudi Arabia",         "AS", 21, 39, "🇸🇦"),
    "7Z":   ("Saudi Arabia",         "AS", 21, 39, "🇸🇦"),
    "A4":   ("Oman",                 "AS", 21, 39, "🇴🇲"),
    "A6":   ("United Arab Emirates", "AS", 21, 39, "🇦🇪"),
    "A7":   ("Qatar",                "AS", 21, 39, "🇶🇦"),
    "A9":   ("Bahrain",              "AS", 21, 39, "🇧🇭"),
    "9K":   ("Kuwait",               "AS", 21, 39, "🇰🇼"),
    "YI":   ("Iraq",                 "AS", 21, 39, "🇮🇶"),
    "EP":   ("Iran",                 "AS", 21, 40, "🇮🇷"),
    # Asia
    "JA":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JB":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JC":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JD":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JE":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JF":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JG":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JH":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JI":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JJ":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JK":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JL":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JM":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JN":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JO":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JP":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JQ":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JR":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JS":   ("Japan",                "AS", 25, 45, "🇯🇵"),
    "JT":   ("Japan",                "AS", 25, 45, "🇯🇵"),  # Mongolia actually but close
    "HL":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "6K":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "6L":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "6M":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "6N":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "DS":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "DT":   ("South Korea",          "AS", 25, 44, "🇰🇷"),
    "BY":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BA":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BD":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BG":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BH":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BI":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BJ":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BL":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BM":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BN":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BO":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BP":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BQ":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BR":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BS":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BT":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BU":   ("China",                "AS", 24, 44, "🇨🇳"),
    "BV":   ("Taiwan",               "AS", 24, 44, "🇹🇼"),
    "VR":   ("Hong Kong",            "AS", 24, 44, "🇭🇰"),
    "XX9":  ("Macao",                "AS", 24, 44, "🇲🇴"),
    "VS6":  ("Hong Kong",            "AS", 24, 44, "🇭🇰"),
    "9V":   ("Singapore",            "AS", 28, 54, "🇸🇬"),
    "9W":   ("Malaysia",             "AS", 28, 54, "🇲🇾"),
    "YB":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YC":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YD":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YE":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YF":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YG":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "YH":   ("Indonesia",            "OC", 28, 51, "🇮🇩"),
    "DU":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "DV":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "DW":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "DX":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "DY":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "DZ":   ("Philippines",          "OC", 27, 50, "🇵🇭"),
    "HS":   ("Thailand",             "AS", 26, 49, "🇹🇭"),
    "E2":   ("Thailand",             "AS", 26, 49, "🇹🇭"),
    "XW":   ("Laos",                 "AS", 26, 49, "🇱🇦"),
    "XV":   ("Vietnam",              "AS", 26, 49, "🇻🇳"),
    "3W":   ("Vietnam",              "AS", 26, 49, "🇻🇳"),
    "XU":   ("Cambodia",             "AS", 26, 49, "🇰🇭"),
    "XY":   ("Myanmar",              "AS", 26, 49, "🇲🇲"),
    "VU":   ("India",                "AS", 22, 41, "🇮🇳"),
    "AT":   ("India",                "AS", 22, 41, "🇮🇳"),
    "AP":   ("Pakistan",             "AS", 21, 41, "🇵🇰"),
    "S2":   ("Bangladesh",           "AS", 26, 41, "🇧🇩"),
    "9N":   ("Nepal",                "AS", 22, 42, "🇳🇵"),
    "A5":   ("Bhutan",               "AS", 26, 41, "🇧🇹"),
    "4S":   ("Sri Lanka",            "AS", 26, 41, "🇱🇰"),
    "8Q":   ("Maldives",             "AS", 26, 41, "🇲🇻"),
    # Africa
    "ZS":   ("South Africa",         "AF", 38, 57, "🇿🇦"),
    "ZR":   ("South Africa",         "AF", 38, 57, "🇿🇦"),
    "ZT":   ("South Africa",         "AF", 38, 57, "🇿🇦"),
    "ZU":   ("South Africa",         "AF", 38, 57, "🇿🇦"),
    "5B":   ("Cyprus",               "AS", 20, 39, "🇨🇾"),
    "H4":   ("Solomon Islands",      "OC", 28, 51, "🇸🇧"),
    "ZL":   ("New Zealand",          "OC", 32, 60, "🇳🇿"),
    "VK":   ("Australia",            "OC", 29, 55, "🇦🇺"),
    "VJ":   ("Australia",            "OC", 29, 55, "🇦🇺"),
    "5N":   ("Nigeria",              "AF", 35, 46, "🇳🇬"),
    "5Z":   ("Kenya",                "AF", 37, 48, "🇰🇪"),
    "9J":   ("Zambia",               "AF", 37, 53, "🇿🇲"),
    "ZW":   ("Zimbabwe",             "AF", 38, 53, "🇿🇼"),
    "Z2":   ("Zimbabwe",             "AF", 38, 53, "🇿🇼"),
    "7Q":   ("Malawi",               "AF", 37, 53, "🇲🇼"),
    "C9":   ("Mozambique",           "AF", 37, 53, "🇲🇿"),
    "3DA":  ("Swaziland",            "AF", 38, 57, "🇸🇿"),
    "7P":   ("Lesotho",              "AF", 38, 57, "🇱🇸"),
    "3B8":  ("Mauritius",            "AF", 39, 53, "🇲🇺"),
    "FR":   ("Reunion",              "AF", 39, 53, "🇷🇪"),
    "TZ":   ("Mali",                 "AF", 35, 46, "🇲🇱"),
    "XT":   ("Burkina Faso",         "AF", 35, 46, "🇧🇫"),
    "TL":   ("Central Africa",       "AF", 36, 47, "🇨🇫"),
    "TR":   ("Gabon",                "AF", 36, 52, "🇬🇦"),
    "TJ":   ("Cameroon",             "AF", 36, 47, "🇨🇲"),
    "9Q":   ("DR Congo",             "AF", 36, 52, "🇨🇩"),
    "9X":   ("Rwanda",               "AF", 36, 52, "🇷🇼"),
    "5X":   ("Uganda",               "AF", 37, 48, "🇺🇬"),
    "ET":   ("Ethiopia",             "AF", 37, 48, "🇪🇹"),
    "6O":   ("Somalia",              "AF", 37, 48, "🇸🇴"),
    "ST":   ("Sudan",                "AF", 34, 48, "🇸🇩"),
    "SU":   ("Egypt",                "AF", 33, 38, "🇪🇬"),
    "CN":   ("Morocco",              "AF", 33, 37, "🇲🇦"),
    "7X":   ("Algeria",              "AF", 33, 37, "🇩🇿"),
    "TS":   ("Tunisia",              "AF", 33, 37, "🇹🇳"),
    "5A":   ("Libya",                "AF", 33, 38, "🇱🇾"),
    # Pacific / Oceania
    "YJ":   ("Vanuatu",              "OC", 28, 56, "🇻🇺"),
    "FK":   ("New Caledonia",        "OC", 28, 56, "🇳🇨"),
    "FO":   ("French Polynesia",     "OC", 31, 63, "🇵🇫"),
    "KH4":  ("Midway",               "OC", 31, 61, "🇺🇲"),
    "KH7":  ("Johnston",             "OC", 31, 61, "🇺🇲"),
    "T2":   ("Tuvalu",               "OC", 28, 65, "🇹🇻"),
    "T30":  ("W. Kiribati",          "OC", 28, 65, "🇰🇮"),
    "T31":  ("Central Kiribati",     "OC", 31, 62, "🇰🇮"),
    "T32":  ("E. Kiribati",          "OC", 31, 61, "🇰🇮"),
    "E5":   ("Cook Islands",         "OC", 32, 62, "🇨🇰"),
    "ZK3":  ("Tokelau",              "OC", 28, 62, "🇹🇰"),
    "5W":   ("Samoa",                "OC", 32, 62, "🇼🇸"),
    "A3":   ("Tonga",                "OC", 32, 62, "🇹🇴"),
    "3D2":  ("Fiji",                 "OC", 28, 56, "🇫🇯"),
    "P2":   ("Papua New Guinea",     "OC", 28, 51, "🇵🇬"),
    "H40":  ("Temotu",               "OC", 28, 51, "🇸🇧"),
    "VK9":  ("Christmas Is.",        "OC", 29, 54, "🇨🇽"),
    "VK0":  ("Heard Is.",            "AF", 38, 68, "🇦🇶"),
}

# Sort by prefix length descending so longer prefixes match first
_SORTED_PREFIXES = sorted(PREFIX_TABLE.keys(), key=len, reverse=True)


def lookup(callsign: str) -> dict:
    """
    Look up a callsign and return DXCC info.
    Strips /P /M /MM /QRP suffixes and portable prefixes like W6/JA1ABC.
    Returns dict with entity, continent, cq_zone, itu_zone, flag.
    """
    if not callsign:
        return {}

    call = callsign.upper().strip()

    # Handle portable prefix: VE3/K6WRJ -> try K6 first, then VE3
    if '/' in call:
        parts = call.split('/')
        # Usually shorter part is the portable prefix
        parts.sort(key=len)
        call = parts[-1]  # use the longer part (actual call)

    # Strip common suffixes
    for suffix in ['/QRP', '/P', '/M', '/MM', '/AM', '/PM']:
        if call.endswith(suffix):
            call = call[:-len(suffix)]
            break

    # Try progressively shorter prefixes
    for length in range(min(5, len(call)), 0, -1):
        prefix = call[:length]
        if prefix in PREFIX_TABLE:
            entity, continent, cq, itu, flag = PREFIX_TABLE[prefix]
            return {
                "entity":    entity,
                "continent": continent,
                "cq_zone":   cq,
                "itu_zone":  itu,
                "flag":      flag,
            }

    return {}


def enrich_spot(spot: dict) -> dict:
    """Add DXCC info to a spot dict in place."""
    info = lookup(spot.get("callsign", ""))
    if info:
        spot.setdefault("dxcc",      info["entity"])
        spot.setdefault("continent", info["continent"])
        spot["cq_zone"]  = info["cq_zone"]
        spot["itu_zone"] = info["itu_zone"]
        spot["flag"]     = info["flag"]
    else:
        spot.setdefault("dxcc",      "")
        spot.setdefault("continent", "")
        spot["flag"] = "📡"
    return spot
